name: run ui automation tests

on: [push]

jobs:

  run-tests:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: create properties file
        run: | 
        echo 'url=https://www.saucedemo.com/'
        echo 'browser=chrome'
        echo 'standard_user=standard_user'
        echo 'password=secret_sauce'
        echo 'wrong_password=wrong_pass'
      - name: download properties file
        uses: actions/upload-artifact@v3.1.0
        with:
          name: properties
          path: ./config.properties
