name: run ui automation tests

on: [push]

jobs:

  run-tests:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: create properties file
        run: touch ./config.properties
      - name: Write values to Properties-file
        uses: christian-draeger/write-properties@1.1.0
        with:
          path: './config.properties'
          property: |
            'url'
            'browser'
            'standard_user'
            'password'
            'wrong_password'
          value: |
            'https://www.saucedemo.com/'
            'chrome'
            'standard_user'
            'secret_sauce'
            'wrong_pass'
      - name: download properties file
        uses: actions/upload-artifact@v3.1.0
        with:
          name: properties
          path: ./config.properties
