name: run ui automation tests

on: [push]

jobs:

  run-tests:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: create properties file
        run: | 
        touch ./config.properties
        echo 'url=https://www.saucedemo.com/' >> ./config.properties
        echo 'browser=chrome' >> ./config.properties
        echo 'standard_user=standard_user' >> ./config.properties
        echo 'password=secret_sauce' >> ./config.properties
        echo 'wrong_password=wrong_pass' >> ./config.properties
      - name: download properties file
        uses: actions/upload-artifact@v3.1.0
        with:
          name: properties
          path: ./config.properties
