name: run ui automation tests

on: [push]

jobs:

  run-tests:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Create and set properties file
        env:
          STANDARD_USER: ${{ secrets.STANDARD_USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: | 
          touch ./config.properties
          echo 'url=https://www.saucedemo.com/' >> ./config.properties
          echo 'browser=chrome' >> ./config.properties
          echo 'standard_user=$STANDARD_USER' >> ./config.properties
          echo 'password=$PASSWORD' >> ./config.properties
          echo 'wrong_password=wrong_pass' >> ./config.properties
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
            java-version: '11'
            distribution: 'temurin'
            cache: maven
      - name: Run tests with Maven
        run: mvn -B package --file pom.xml
      - name: Upload Reports
        uses: actions/upload-artifact@v3.1.0
        with:
            name: test report
            path: ./target/cucumber-reports/index.html